### PR TITLE
Update systems.js

### PR DESCRIPTION
**Pull request by YenBenGrey**
Added Crucible to the list of RPG systems, however not sure what the return is, I have tried to look in the console but I can't find it, it is called 'stride' in the game. They measure in squares and not feet or metres. It also needs to be tied to action points. SO much is free movement, then an AP per movement of the actor. But no problem if it can't be done yet.

### CODE REVIEW

**Comment by manuelVo** [comment]
The value behind the `return` must be whatever you would be putting into the Speed Provider Settings (put into quotation marks `"` and followed by a semicolon `;`). If you don't know what the right settings are or how to find them, it's best to consult with the Crucible community. There's probably someone there who can help you with that.

**Comment by manuelVo** [comment]
Look good :)

Only two things are still missing: A return value for the default multiplier (use 0 if there is no use of that multiplier in crucible) and a `;` at the end of the line with the `return` you've added

**Comment by YenBenGrey** [comment]
Thank you for this lesson in GitHub. Think I need to visit Ko-Fi :)

**Comment by manuelVo** [comment]
Perfect. I've merged your changes into the module. They will be part of the next Drag Ruler release :)

**Pull request merged**
